/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 1                                                     *
* Dimensions:  40 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bm1;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colors1[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Pal1 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colors1[0]
};

static GUI_CONST_STORAGE unsigned char _ac1[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, __XXXX__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ___XXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X___XX_X, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXX___XX, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXX_XX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX_X, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXX__, XX_XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXX_, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, _XX_XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ____XXXX, __X_XXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, __XXXXXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XX__XX__, XXXXXXXX, X_X_XXXX, XXXXXXXX,
  XXXXXXXX, X___X__X, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, __XX__XX, XXX___XX, X__XXXXX, XXXXXXXX,
  XXXXXXX_, __XX_XXX, XXX___XX, X_XXXXXX, XXXX_XXX,
  XXXXXXX_, _XX__XXX, XXX___XX, __XXXXXX, XXXX_XXX,
  XXXXXX__, XXX_XXXX, _XXXXXXX, _XXXXXXX, XXX__XXX,
  XXXXX___, XX__XXXX, __XXXXXX, XXXXXXXX, XX___XXX,
  XXXXX___, XX_XXXXX, X__XXXXX, XXXXXXXX, _____XXX,
  XXXXX__X, X__XXXXX, X____XXX, XXXXXX__, _X__XXXX,
  XXXXX_XX, X__XXXXX, XX_X____, _______X, XX__XXXX,
  XXXXX__X, X__XXXXX, XXX__XX_, ____XX_X, XX_XXXXX,
  XXXXXX__, X__XXXXX, XXXX_XX_, XX_XXX_X, X__XXXXX,
  XXXXXXX_, ___XXXXX, XXXXXX__, _X_XXX__, __XXXXXX,
  XXXXXXX_, ___XXXXX, XXXXXXXX, ________, _XXXXXXX,
  XXXXXXXX, ___XXXXX, XXXXXXXX, XXXXX___, _XXXXXXX,
  XXXXXXXX, X___XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XX__XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bm1 = {
  40, // xSize
  40, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _ac1,  // Pointer to picture data (indices)
  &_Pal1   // Pointer to palette
};

/*************************** End of file ****************************/
