/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.24.                           *
*        Compiled Jan 27 2014, 11:27:47                              *
*        (c) 1998 - 2013 Segger Microcontroller GmbH && Co. KG       *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 2                                                     *
* Dimensions:  40 * 40                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bm2;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colors2[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Pal2 = {
  2,  // Number of entries
  0,  // No transparency
  &_Colors2[0]
};

static GUI_CONST_STORAGE unsigned char _ac2[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX___X, XXXXXXXX,
  XXXXXXX_, ___XXXXX, XXXXXXXX, XXXXX___, XXXXXXXX,
  XXXXXXX_, ________, XXXXXXXX, XXXXX___, _XXXXXXX,
  XXXXXX__, __XXX_X_, __XXXXXX, XXXXX___, _XXXXXXX,
  XXXXX__X, X_XXX_XX, _XX_XXXX, XXXXX__X, __XXXXXX,
  XXXXX_XX, X_XX____, _XX__XXX, XXXXX__X, X__XXXXX,
  XXXX__XX, X_______, ____X_XX, XXXXX__X, XX_XXXXX,
  XXXX__X_, __XXXXXX, XXX____X, XXXXX__X, X__XXXXX,
  XXX_____, XXXXXXXX, XXXXX__X, XXXXX_XX, ___XXXXX,
  XXX___XX, XXXXXXXX, XXXXXX__, XXXX__XX, ___XXXXX,
  XXX__XXX, XXXXXXX_, XXXXXXX_, XXXX_XXX, __XXXXXX,
  XXX_XXXX, XXXXXX__, XX___XXX, XXX__XX_, _XXXXXXX,
  XXX_XXXX, XXXXXX_X, XX___XXX, XXX_XX__, _XXXXXXX,
  XXXXXXXX, XXXXX__X, XX___XXX, XX__XX__, XXXXXXXX,
  XXXXXXXX, XXXXX__X, XXXXXXXX, X__X___X, XXXXXXXX,
  XXXXXXXX, XXXX_X_X, XXXXXXXX, __XX__XX, XXXXXXXX,
  XXXXXXXX, XXXX___X, XXXXXX__, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXX_X__, XXXX____, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX_XX_, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, __XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX___, X_XXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX__X, XX_XXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, XX___XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, X_XX___X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, _XXXX___, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, __XXXX__, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, ________, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bm2 = {
  40, // xSize
  40, // ySize
  5, // BytesPerLine
  1, // BitsPerPixel
  _ac2,  // Pointer to picture data (indices)
  &_Pal2   // Pointer to palette
};

/*************************** End of file ****************************/
