/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.24                       *
*        Compiled Jan 27 2014, 11:28:13                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: YH31.c                                                *
* Font:        微软雅黑                                              *
* Height:      31                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  31                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\code\UCGUIFontTool--执行程序\新风净化系统1.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYH31;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4E00[ 93] = { /* code 4E00, <CJK Ideograph, First> */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4E09[ 93] = { /* code 4E09 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4E8C[ 93] = { /* code 4E8C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4E94[ 93] = { /* code 4E94 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XXX_____,________,
  ________,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ______XX,XX______,_XXX____,
  ______XX,XX______,_XXX____,
  ______XX,XX______,_XXX____,
  ______XX,X_______,_XXX____,
  ______XX,X_______,_XXX____,
  ______XX,X_______,_XXX____,
  _____XXX,X_______,_XXX____,
  _____XXX,X_______,_XXX____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4EAE[ 93] = { /* code 4EAE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXX___,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXX_,________,_XXX____,
  ____XXX_,________,_XXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX____,________,____XXX_,
  _XXX__XX,XXXXXXXX,X___XXX_,
  ______XX,XXXXXXXX,X_______,
  ______XX,X_____XX,X_______,
  ______XX,X_____XX,X____X__,
  _____XXX,X_____XX,X____XXX,
  ____XXXX,______XX,X___XXX_,
  _XXXXXXX,______XX,XXXXXXX_,
  _XXXXX__,______XX,XXXXXXX_,
  __XX____,_______X,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_4F5C[ 93] = { /* code 4F5C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____XX_,___XX___,________,
  _____XXX,___XXX__,________,
  ____XXXX,__XXXX__,________,
  ____XXX_,__XXX___,________,
  ____XXX_,__XXXXXX,XXXXXXXX,
  ___XXX__,_XXXXXXX,XXXXXXXX,
  ___XXX__,_XXXXXXX,XXXXXXXX,
  __XXXX__,XXXX_XXX,________,
  __XXXX__,XXX__XXX,________,
  _XXXXX_X,XXX__XXX,________,
  _XXXXX_X,XX___XXX,XXXXXX__,
  XXXXXX__,XX___XXX,XXXXXX__,
  _XXXXX__,X____XXX,XXXXXX__,
  _XXXXX__,_____XXX,________,
  _X_XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,XXXXXXX_,
  ___XXX__,_____XXX,XXXXXXX_,
  ___XXX__,_____XXX,XXXXXXX_,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5149[ 93] = { /* code 5149 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXXX__,________,
  ____X___,__XXXX__,___X____,
  __XXXX__,__XXXX__,__XXX___,
  __XXXXX_,__XXXX__,_XXXXX__,
  ___XXXXX,__XXXX__,XXXXX___,
  ____XXXX,X_XXXX_X,XXXX____,
  _____XXX,__XXXX__,XXX_____,
  ______X_,__XXXX__,_X______,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,XX___XXX,________,
  ______XX,XX___XXX,________,
  ______XX,XX___XXX,________,
  ______XX,XX___XXX,____XX__,
  ______XX,XX___XXX,____XXXX,
  _____XXX,X____XXX,____XXX_,
  ____XXXX,X____XXX,____XXX_,
  ___XXXXX,_____XXX,X__XXXX_,
  __XXXXXX,_____XXX,XXXXXXX_,
  _XXXXXX_,_____XXX,XXXXXX__,
  __XXXX__,_______X,XXXXX___,
  __XX____,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5168[ 93] = { /* code 5168 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXXX__,________,
  ________,_XXXXX__,________,
  ________,_XXXXXX_,________,
  ________,XXXXXXXX,________,
  ______XX,XXX__XXX,X_______,
  _____XXX,XX____XX,XXX_____,
  ___XXXXX,X______X,XXXX____,
  __XXXXXX,________,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX_XX,XXXXXXXX,XX_XXXX_,
  __X___XX,XXXXXXXX,XX___X__,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_516D[ 93] = { /* code 516D */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,_XXXX___,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,___XXXX_,________,
  ________,___XX___,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  _______X,________,X_______,
  ______XX,XX____XX,XX______,
  ______XX,XX____XX,XX______,
  _____XXX,X______X,XXX_____,
  _____XXX,X______X,XXXX____,
  ____XXXX,________,XXXX____,
  ___XXXXX,________,_XXXX___,
  ___XXXX_,________,_XXXXX__,
  __XXXX__,________,__XXXX__,
  _XXXXX__,________,__XXXXX_,
  _XXXX___,________,___XXXX_,
  _XXX____,________,____XXX_,
  ___X____,________,____X___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5173[ 93] = { /* code 5173 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,X_______,
  _____XXX,X______X,XXX_____,
  _____XXX,X______X,XXX_____,
  ______XX,XX____XX,XX______,
  _______X,XX___XXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_XXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,XXXXXXXX,________,
  ______XX,XXX__XXX,X_______,
  _____XXX,XX____XX,XXX_____,
  ___XXXXX,X______X,XXXXX___,
  _XXXXXXX,________,XXXXXXX_,
  __XXXX__,________,_XXXXXX_,
  __XX____,________,____XX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_51C0[ 93] = { /* code 51C0 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXXX__,________,
  __X_____,__XXX___,________,
  _XXX____,_XXXXXXX,XXXX____,
  _XXX____,XXXXXXXX,XXXX____,
  _XXXX__X,XXXXXXXX,XXXX____,
  __XXXX_X,XXX_____,XXX_____,
  __XXXXXX,XX_____X,XXX_____,
  ___XX__X,XXXXXXXX,XXXXXX__,
  ___X____,XXXXXXXX,XXXXXX__,
  ________,XXXXXXXX,XXXXXX__,
  ________,_____XXX,___XXX__,
  ______XX,XXXXXXXX,XXXXXXXX,
  ___XX_XX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXX__,_____XXX,___XXX__,
  __XXX__X,XXXXXXXX,XXXXXX__,
  __XXX__X,XXXXXXXX,XXXXXX__,
  _XXXX__X,XXXXXXXX,XXXXXX__,
  _XXX____,_____XXX,___XXX__,
  _XXX____,_____XXX,________,
  XXXX____,____XXXX,________,
  _XX_____,_XXXXXXX,________,
  __X_____,_XXXXXX_,________,
  ________,_XXXXX__,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_51C6[ 93] = { /* code 51C6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XX____,X_______,
  __X_____,_XXXX_XX,XX______,
  XXXX____,_XXX___X,XXX_____,
  _XXX____,_XXX____,XXX_____,
  _XXXX___,XXXXXXXX,XXXXXXX_,
  __XXX___,XXXXXXXX,XXXXXXX_,
  __XXXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XXX____X,XX______,
  ___X__XX,XXX____X,XX______,
  _____XXX,XXXXXXXX,XXXXXXX_,
  _____XXX,XXXXXXXX,XXXXXXX_,
  ______XX,XXXXXXXX,XXXXXXX_,
  ___XX_X_,XXX____X,XX______,
  ___XXX__,XXX____X,XX______,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  __XXXX__,XXXXXXXX,XXXXXXX_,
  __XXX___,XXXXXXXX,XXXXXXX_,
  __XXX___,XXX____X,XX______,
  _XXXX___,XXX____X,XX______,
  _XXX____,XXXXXXXX,XXXXXXX_,
  XXXX____,XXXXXXXX,XXXXXXX_,
  _XXX____,XXXXXXXX,XXXXXXX_,
  __X_____,XXX_____,________,
  ________,XXX_____,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5206[ 93] = { /* code 5206 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X______X,________,
  _______X,XXX__XXX,X_______,
  _______X,XXX___XX,XX______,
  ______XX,XX____XX,XX______,
  _____XXX,X______X,XXX_____,
  ____XXXX,X_______,XXXX____,
  ___XXXXX,________,_XXXX___,
  _XXXXXX_,________,_XXXXXX_,
  XXXXXX__,________,__XXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __X_XXXX,XXXXXXXX,XXXX_X__,
  ____XXXX,XXXXXXXX,XXXX____,
  _______X,XX______,XXXX____,
  _______X,XX______,XXXX____,
  _______X,XX______,XXXX____,
  ______XX,XX______,XXXX____,
  ______XX,XX______,XXXX____,
  ______XX,XX______,XXXX____,
  _____XXX,X_______,XXX_____,
  ____XXXX,X_______,XXX_____,
  __XXXXXX,___XXXXX,XXX_____,
  _XXXXXX_,___XXXXX,XXX_____,
  __XXXX__,___XXXXX,XX______,
  ___X____,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5316[ 93] = { /* code 5316 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______XX,____XXX_,________,
  ______XX,X___XXX_,________,
  _____XXX,X___XXX_,________,
  _____XXX,____XXX_,____X___,
  ____XXXX,____XXX_,___XXX__,
  ____XXX_,____XXX_,__XXXXX_,
  ___XXXX_,____XXX_,_XXXXX__,
  ___XXXX_,____XXX_,XXXXX___,
  __XXXXX_,____XXXX,XXXX____,
  _XXXXXX_,____XXXX,XXX_____,
  _XXXXXX_,____XXXX,XX______,
  _XXXXXX_,___XXXXX,X_______,
  _XX_XXX_,__XXXXXX,________,
  _X__XXX_,XXXXXXX_,________,
  _X__XXXX,XXXXXXX_,________,
  ____XXX_,XXX_XXX_,________,
  ____XXX_,_X__XXX_,____XX__,
  ____XXX_,____XXX_,____XXXX,
  ____XXX_,____XXX_,____XXX_,
  ____XXX_,____XXX_,____XXX_,
  ____XXX_,____XXXX,___XXXX_,
  ____XXX_,____XXXX,XXXXXXX_,
  ____XXX_,_____XXX,XXXXXX__,
  ____XXX_,______XX,XXXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_53CD[ 93] = { /* code 53CD */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_______X,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXX_,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___XXXX_,__X_____,__XXXX__,
  ___XXX__,XXX_____,__XXXX__,
  ___XXX__,XXXX____,_XXXX___,
  ___XXX__,_XXXX___,XXXX____,
  ___XXX__,_XXXX___,XXXX____,
  ___XXX__,__XXXX_X,XXX_____,
  ___XXX__,___XXXXX,XX______,
  __XXXX__,___XXXXX,X_______,
  __XXXX__,___XXXXX,XX______,
  _XXXX___,_XXXXXXX,XXXX____,
  _XXXX__X,XXXXX__X,XXXXXX__,
  XXXXXXXX,XXXX____,_XXXXXX_,
  _XXX__XX,XX______,__XXXXX_,
  _______X,________,____XX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_53D6[ 93] = { /* code 53D6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXX____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,XXX_XXXX,XXXXXXX_,
  _XXXX___,XXX__XXX,____XXX_,
  _XXXXXXX,XXX__XXX,___XXXX_,
  _XXXXXXX,XXX__XXX,___XXX__,
  _XXXXXXX,XXX__XXX,___XXX__,
  _XXXX___,XXX__XXX,___XXX__,
  _XXXX___,XXX__XXX,__XXXX__,
  _XXXX___,XXX__XXX,X_XXX___,
  _XXXXXXX,XXX___XX,X_XXX___,
  _XXXXXXX,XXX___XX,XXXXX___,
  _XXXXXXX,XXX___XX,XXXX____,
  _XXXX___,XXX____X,XXXX____,
  _XXXX___,XXX____X,XXX_____,
  _XXXX___,XXXX___X,XXXX____,
  _XXXXXXX,XXXX__XX,XXXXX___,
  XXXXXXXX,XXXX_XXX,XXXXX___,
  _XXXXXXX,XXX_XXXX,X_XXXXX_,
  _XX_____,XXX_XXXX,___XXXX_,
  ________,XXX_XXX_,____XXX_,
  ________,XXX__X__,_____X__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_56DB[ 93] = { /* code 56DB */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX___,XXX__XXX,___XXXX_,
  _XXXX__X,XXX__XXX,___XXXX_,
  _XXXX__X,XX___XXX,___XXXX_,
  _XXXX__X,XX___XXX,XXXXXXX_,
  _XXXX_XX,XX___XXX,XXXXXXX_,
  _XXXXXXX,X_____XX,XXXXXXX_,
  _XXXX_XX,________,___XXXX_,
  _XXXX___,________,___XXXX_,
  _XXXX___,________,___XXXX_,
  _XXXX___,________,___XXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXX___,________,___XXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5A74[ 93] = { /* code 5A74 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXX__XXX,XXXXXX__,
  __XXXXXX,XXX__XXX,XXXXXX__,
  __XX____,_XX__XX_,____XX__,
  __XX_XXX,_XX__XX_,XXX_XX__,
  __XX_XXX,_XX__XX_,XXX_XX__,
  __XX_XXX,_XX__XX_,XXX_XX__,
  __XX_XX_,_XX__XX_,XX__XX__,
  __XX_XX_,_XX__XX_,XX__XX__,
  ____XXXX,X______X,XXX_____,
  __XXXXXX,XX____XX,XXXXX___,
  XXXXXX__,XXXXXXXX,X_XXXX__,
  _XXXX___,_XX_XXXX,____XXX_,
  __X_____,XXXX_X__,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _____XXX,X______X,XXX_____,
  ____XXXX,XX____XX,XX______,
  _____XXX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXX_____,XXXXXX__,
  __XXXX__,________,___XX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5C4F[ 93] = { /* code 5C4F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXX__,________,___XXX__,
  __XXXX__,________,___XXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXX__,_XXX____,XXXX____,
  __XXXX__,_XXXX___,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXX_XX,XXXXXXXX,XXXXXXX_,
  __XXX_XX,XXXXXXXX,XXXXXXX_,
  __XXX___,_XXX____,XXX_____,
  __XXX___,_XXX____,XXX_____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXX___,_XXX____,XXX_____,
  _XXXX___,XXXX____,XXX_____,
  _XXX___X,XXX_____,XXX_____,
  __XX___X,XXX_____,XXX_____,
  ________,XX______,XXX_____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5DE5[ 93] = { /* code 5DE5 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5E55[ 93] = { /* code 5E55 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XX____XX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _______X,XX____XX,X_______,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,XXX_____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ____XXXX,__XXXX__,XXX_____,
  __XXXXXX,__XXXX__,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  __X_XXX_,__XXXX__,_XXX_XX_,
  ____XXX_,__XXXX_X,XXXX____,
  ____XXX_,__XXXX_X,XXX_____,
  ________,__XXXX__,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5E74[ 93] = { /* code 5E74 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______XX,X_______,________,
  _____XXX,X_______,________,
  _____XXX,X_______,________,
  ____XXXX,XXXXXXXX,XXXXXXX_,
  ____XXXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXX_,____XXX_,________,
  _XXXXX__,____XXX_,________,
  _XXXX___,____XXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  __X_XXXX,XXXXXXXX,XXXXXX__,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____XXX_,____XXX_,________,
  ____XXX_,____XXX_,________,
  ____XXX_,____XXX_,________,
  ____XXX_,____XXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,____XXX_,________,
  ________,____XXX_,________,
  ________,____XXX_,________,
  ________,____XXX_,________,
  ________,____XXX_,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5EA6[ 93] = { /* code 5EA6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXX_,________,
  ________,___XXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXX___,________,________,
  __XXX___,XXX_____,_XXX____,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXX___,XXX_____,_XXX____,
  __XXX___,XXXXXXXX,XXXX____,
  __XXX___,XXXXXXXX,XXXX____,
  __XXX___,XXXXXXXX,XXXX____,
  __XXX___,________,________,
  __XXX_XX,XXXXXXXX,XXXXX___,
  __XXX_XX,XXXXXXXX,XXXXX___,
  _XXXX_XX,XXXXXXXX,XXXXX___,
  _XXX____,XXX_____,_XXXX___,
  _XXX____,_XXXX__X,XXXX____,
  _XXX____,__XXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  _XX__XXX,XXXXXXXX,XXXXXXX_,
  __X__XXX,XX______,__XXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5F00[ 93] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ______XX,X______X,XXX_____,
  ______XX,X______X,XXX_____,
  _____XXX,X______X,XXX_____,
  _____XXX,X______X,XXX_____,
  ____XXXX,_______X,XXX_____,
  ___XXXXX,_______X,XXX_____,
  __XXXXXX,_______X,XXX_____,
  _XXXXXX_,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  ___X____,_______X,XXX_____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5F0F[ 93] = { /* code 5F0F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XXXX,___X____,
  ________,____XXXX,_XXXX___,
  ________,____XXXX,__XXXX__,
  ________,_____XXX,___XX___,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,_____XXX,________,
  ________,_____XXX,________,
  ________,_____XXX,________,
  _XXXXXXX,XXXX_XXX,________,
  _XXXXXXX,XXXX_XXX,X_______,
  _XXXXXXX,XXXX_XXX,X_______,
  _____XXX,_____XXX,X_______,
  _____XXX,______XX,X_______,
  _____XXX,______XX,X_______,
  _____XXX,______XX,X_______,
  _____XXX,_XXXX_XX,X___XXX_,
  ____XXXX,XXXXX_XX,XX__XXX_,
  XXXXXXXX,XXXXX__X,XX__XXX_,
  _XXXXXXX,X______X,XXX_XXX_,
  _XX_____,_______X,XXXXXXX_,
  ________,________,XXXXXX__,
  ________,________,_XXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_5FAA[ 93] = { /* code 5FAA */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,________,_XXXXXX_,
  ____XXX_,XXXXXXXX,XXXXXXX_,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  __XXXX__,XXXXXXXX,XXX_____,
  _XXXX___,XX______,XXX_____,
  XXXXX___,XXXXXXXX,XXXXXXX_,
  _XXX____,XXXXXXXX,XXXXXXX_,
  _____XX_,XXXXXXXX,XXXXXXX_,
  ____XXXX,XX______,XXX_____,
  ___XXXX_,XX__XXXX,XXXXXXX_,
  __XXXX__,XX__XXXX,XXXXXXX_,
  _XXXXX__,XX__XX__,____XXX_,
  XXXXXX__,XX__XXXX,XXXXXXX_,
  _XXXXX__,XX__XXXX,XXXXXXX_,
  _X_XXX_X,XX__XX__,____XXX_,
  ___XXX_X,XX__XXXX,XXXXXXX_,
  ___XXX_X,XX__XXXX,XXXXXXX_,
  ___XXX_X,XX__XX__,____XXX_,
  ___XXXXX,XX__XX__,____XXX_,
  ___XXXXX,X___XXXX,XXXXXXX_,
  ___XXXXX,X___XXXX,XXXXXXX_,
  ___XXX_X,____XX__,____XXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6094[ 93] = { /* code 6094 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,__XXXX__,________,
  ___XXX__,__XXX___,________,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXXX_,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXX_____,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXX_X,_XXXXXXX,XXXXXX__,
  _XXXXX__,_XXXXXXX,XXXXXX__,
  _XXXXX__,_XXX__XX,X__XXX__,
  XX_XXX__,_XXX___X,X__XXX__,
  XX_XXX_X,XXXXXXXX,XXXXXXXX,
  ___XXX_X,XXXXXXXX,XXXXXXXX,
  ___XXX_X,XXXXXXXX,XXXXXXXX,
  ___XXX__,XXX___XX,___XXX__,
  ___XXX__,XXX__XXX,X__XXX__,
  ___XXX__,XXX___XX,X__XXX__,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,______XX,XXXXXX__,
  ___XXX__,______XX,XXXXX___,
  ___XXX__,______XX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_62E9[ 93] = { /* code 62E9 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  _XXXXXXX,___XX___,__XXXX__,
  _XXXXXXX,__XXXX__,_XXXX___,
  _XXXXXXX,___XXXXX,XXXX____,
  ___XXX__,____XXXX,XXX_____,
  ___XXX__,__XXXXXX,XXXX____,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXX__,_XXXXXX_,
  ___XXXXX,_XX___XX,X___XXX_,
  XXXXXXXX,______XX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,______XX,X_______,
  ___XXX__,______XX,X_______,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX__,______XX,X_______,
  _XXXXX__,______XX,X_______,
  _XXXX___,______XX,X_______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6309[ 93] = { /* code 6309 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,______XX,X_______,
  ___XXX__,_____XXX,X_______,
  ___XXX__,______XX,X_______,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXX____,____XXX_,
  _XXXXXXX,_XXX_XX_,____XXX_,
  ___XXX__,____XXXX,________,
  ___XXX__,____XXX_,________,
  ___XXX__,XXXXXXXX,XXXXXXXX,
  ___XXXXX,XXXXXXXX,XXXXXXXX,
  __XXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,___XXX__,__XXX___,
  _XXXXX__,__XXX___,__XXX___,
  _X_XXX__,__XXX___,_XXXX___,
  ___XXX__,_XXXXX__,XXXX____,
  ___XXX__,__XXXXXX,XXXX____,
  ___XXX__,____XXXX,XXX_____,
  ___XXX__,_____XXX,XXXX____,
  ___XXX__,__XXXXXX,XXXXXX__,
  _XXXXX_X,XXXXXXX_,__XXXXX_,
  _XXXXX__,XXXXXX__,___XXXX_,
  _XXXX___,_XX_____,_____X__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_63D0[ 93] = { /* code 63D0 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXX____,___XXX__,
  XXXXXXXX,_XXXXXXX,XXXXXX__,
  XXXXXXXX,_XXXXXXX,XXXXXX__,
  XXXXXXXX,_XXX____,___XXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  ___XXXX_,________,________,
  ___XXXX_,XXXXXXXX,XXXXXXXX,
  XXXXXXX_,XXXXXXXX,XXXXXXXX,
  XXXXXX_X,XXXXXXXX,XXXXXXXX,
  XX_XXX__,______XX,X_______,
  ___XXX__,__XX__XX,XXXXXXX_,
  ___XXX__,_XXX__XX,XXXXXXX_,
  ___XXX__,_XXX__XX,XXXXXXX_,
  ___XXX__,_XXXX_XX,X_______,
  ___XXX__,XXXXXXXX,X_______,
  XXXXXX_X,XXXXXXXX,XXXXXXXX,
  _XXXXX_X,XX__XXXX,XXXXXXX_,
  _XXXX___,_X____XX,XXXXXXX_,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6574[ 93] = { /* code 6574 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______XX,_______X,XX______,
  _XXXXXXX,XXXXX__X,X_______,
  _XXXXXXX,XXXXX_XX,XXXXXXX_,
  ______XX,______XX,XXXXXXX_,
  _XXXXXXX,XXXX_XXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,___XXX__,
  _XXX__XX,__XXXXXX,X__XXX__,
  _XXX__XX,__XX_XXX,XX_XX___,
  _XXXXXXX,XXXX___X,XXXXX___,
  _XXXXXXX,XXXX____,XXXX____,
  ____XXXX,_X_____X,XXXXX___,
  __XXXXXX,XXXX_XXX,XXXXXXXX,
  XXXX__XX,_XXXXXXX,X__XXXX_,
  _XX_____,___X__X_,_____XX_,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XXX__,________,
  ____XXX_,___XXXXX,XXXXX___,
  ____XXX_,___XXXXX,XXXXX___,
  ____XXX_,___XXX__,________,
  ____XXX_,___XXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_65B0[ 93] = { /* code 65B0 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____XXX,________,_____XX_,
  _____XXX,________,_XXXXXX_,
  _XXXXXXX,XXXX__XX,XXXXXXX_,
  _XXXXXXX,XXXX__XX,XXXXXX__,
  _XXXXXXX,XXXX__XX,XXX_____,
  ___XX___,_X____XX,X_______,
  __XXX___,XXX___XX,X_______,
  ___XXX_X,XXX___XX,X_______,
  _XXXXXXX,XXXXX_XX,XXXXXXXX,
  _XXXXXXX,XXXXX_XX,XXXXXXXX,
  _XXXXXXX,XXXXX_XX,XXXXXXXX,
  _____XXX,______XX,X__XXX__,
  _XXXXXXX,XXXX__XX,X__XXX__,
  _XXXXXXX,XXXX__XX,X__XXX__,
  _XXXXXXX,XXXX__XX,X__XXX__,
  _____XXX,_____XXX,X__XXX__,
  __XX_XXX,__X__XXX,___XXX__,
  __XXXXXX,XXXX_XXX,___XXX__,
  _XXX_XXX,_XXX_XXX,___XXX__,
  _XXX_XXX,__X_XXXX,___XXX__,
  XXX__XXX,____XXX_,___XXX__,
  __XXXXXX,___XXXX_,___XXX__,
  ___XXXXX,___XXXX_,___XXX__,
  ____XXX_,_____X__,___XXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_65E5[ 93] = { /* code 65E5 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_65F6[ 93] = { /* code 65F6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXX___,XXXXXXXX,XXXXXXXX,
  _XXXX___,XXXXXXXX,XXXXXXXX,
  _XXXX___,XXXXXXXX,XXXXXXXX,
  _XXXX___,XXX_____,__XXXX__,
  _XXXX___,XXX__X__,__XXXX__,
  _XXXXXXX,XXXXXX__,__XXXX__,
  _XXXXXXX,XXX_XXX_,__XXXX__,
  _XXXXXXX,XXX_XXXX,__XXXX__,
  _XXXX___,XXX__XXX,__XXXX__,
  _XXXX___,XXX__XXX,X_XXXX__,
  _XXXX___,XXX___XX,X_XXXX__,
  _XXXX___,XXX___XX,XXXXXX__,
  _XXXX___,XXX____X,__XXXX__,
  _XXXX___,XXX_____,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXXXXX,XXX_____,__XXXX__,
  _XXXX___,XXX__XXX,XXXXX___,
  _XXXX___,XXX__XXX,XXXXX___,
  ________,______XX,XXXX____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_661F[ 93] = { /* code 661F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXX_,___XXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  _XXXX___,___XXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  __X_XXXX,XXXXXXXX,XXXXXX__,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ________,___XXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6708[ 93] = { /* code 6708 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,________,__XXX___,
  ____XXXX,________,__XXX___,
  ____XXXX,________,__XXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,________,__XXX___,
  ____XXXX,________,__XXX___,
  ____XXX_,________,__XXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____XXX_,________,__XXX___,
  ___XXXX_,________,__XXX___,
  ___XXXX_,________,__XXX___,
  __XXXXX_,________,__XXX___,
  __XXXX__,________,_XXXX___,
  _XXXXX__,____XXXX,XXXXX___,
  __XXX___,____XXXX,XXXXX___,
  ___X____,_____XXX,XXXX____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_671F[ 93] = { /* code 671F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXX___,_XXX____,________,
  __XXX___,_XXX__XX,XXXXXX__,
  _XXXXXXX,XXXXX_XX,XXXXXX__,
  _XXXXXXX,XXXXX_XX,XXXXXX__,
  _XXXXXXX,XXXXX_XX,X___XX__,
  __XXX___,_XXX__XX,X___XX__,
  __XXX___,_XXX__XX,X___XX__,
  __XXXXXX,XXXX__XX,XXXXXX__,
  __XXXXXX,XXXX__XX,XXXXXX__,
  __XXXXXX,XXXX__XX,XXXXXX__,
  __XXX___,_XXX__XX,X___XX__,
  __XXX___,_XXX__XX,X___XX__,
  __XXXXXX,XXXX__XX,X___XX__,
  __XXXXXX,XXXX__XX,X___XX__,
  __XXXXXX,XXXX__XX,XXXXXX__,
  __XXX___,_XXX__XX,XXXXXX__,
  __XXX___,_XXX_XXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,____XX__,
  XXXXXXXX,XXXXXXXX,____XX__,
  XXXXXXXX,XXXXXXXX,____XX__,
  ___XX___,XX___XXX,___XXX__,
  _XXXXX_X,XXX_XXX_,XXXXXX__,
  _XXXX___,_XXXXXX_,_XXXXX__,
  __X_____,__X_XX__,_XXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_673A[ 93] = { /* code 673A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XXX__,__XXXXXX,XXXX____,
  ___XXX__,__XXXXXX,XXXX____,
  ___XXX__,__XXXXXX,XXXX____,
  _XXXXXXX,X_XXX___,_XXX____,
  _XXXXXXX,X_XXX___,_XXX____,
  _XXXXXXX,X_XXX___,_XXX____,
  ___XXX__,__XXX___,_XXX____,
  ___XXX__,__XXX___,_XXX____,
  __XXXX__,__XXX___,_XXX____,
  __XXXXX_,__XXX___,_XXX____,
  __XXXXXX,X_XXX___,_XXX____,
  _XXXXXXX,XXXXX___,_XXX____,
  _XXXXX_X,X_XXX___,_XXX____,
  XXXXXX__,__XXX___,_XXX_X__,
  _XXXXX__,__XXX___,_XXX_XXX,
  _XXXXX__,__XXX___,_XXX_XXX,
  _X_XXX__,_XXXX___,_XXX_XXX,
  _X_XXX__,_XXXX___,_XXX_XX_,
  ___XXX__,XXXX____,_XXX_XX_,
  ___XXX__,XXXX____,_XXXXXX_,
  ___XXX_X,XXX_____,_XXXXXX_,
  ___XXX__,XXX_____,_XXXXX__,
  ___XXX__,_X______,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6807[ 93] = { /* code 6807 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  XXXXXXXX,________,________,
  XXXXXXXX,________,________,
  XXXXXXXX,________,________,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  __XXXX__,XXXXXXXX,XXXXXXX_,
  __XXXX__,XXXXXXXX,XXXXXXX_,
  __XXXXX_,______XX,X_______,
  _XXXXXXX,X_____XX,X_______,
  _XXXXXXX,__XX__XX,X___X___,
  XXXXXX_X,__XXX_XX,X_XXX___,
  XXXXXX__,_XXX__XX,X__XXX__,
  _X_XXX__,_XXX__XX,X__XXX__,
  _X_XXX__,_XXX__XX,X__XXXX_,
  ___XXX__,XXX___XX,X___XXX_,
  ___XXX__,XXX___XX,X___XXX_,
  ___XXX_X,XXX___XX,X___XXXX,
  ___XXX__,_X____XX,X____X__,
  ___XXX__,___XXXXX,X_______,
  ___XXX__,___XXXXX,X_______,
  ___XXX__,___XXXXX,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6A21[ 93] = { /* code 6A21 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,___XXX__,__XX____,
  ___XXX__,___XXX__,__XX____,
  ___XXX__,XXXXXXXX,XXXXXXXX,
  ___XXX__,XXXXXXXX,XXXXXXXX,
  ___XXX__,___XXX__,__XX____,
  ___XXX__,___XXX__,__XX____,
  _XXXXXXX,________,________,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXX____,____XXX_,
  __XXXXX_,_XXXXXXX,XXXXXXX_,
  __XXXXXX,_XXXXXXX,XXXXXXX_,
  __XXXXXX,XXXX____,____XXX_,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  XXXXXX_X,_XXXXXXX,XXXXXXX_,
  XXXXXX__,______XX,X_______,
  _X_XXX__,______XX,X_______,
  _X_XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  ___XXX__,____XXXX,XXX_____,
  ___XXX__,__XXXXX_,XXXXX___,
  ___XXX_X,XXXXXX__,_XXXXXXX,
  ___XXX__,XXXXX___,___XXXX_,
  ___XXX__,_X______,_____X__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6BCD[ 93] = { /* code 6BCD */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXX_,___X____,__XXX___,
  ___XXX__,__XXX___,__XXX___,
  ___XXX__,__XXXX__,__XXX___,
  ___XXX__,___XXXX_,__XXX___,
  ___XXX__,____XX__,__XXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  __XXXX__,__XX____,__XXX___,
  __XXXX__,_XXXX___,__XXX___,
  __XXXX__,_XXXXX__,__XXX___,
  __XXXX__,__XXXX__,__XXX___,
  __XXXX__,___XX___,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,_XXXX___,
  ________,__XXXXXX,XXXXX___,
  ________,__XXXXXX,XXXX____,
  ________,___XXXXX,XXX_____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_6D88[ 93] = { /* code 6D88 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XX____,_____XXX,X_______,
  _XXXX___,X____XXX,X___X___,
  __XXXX_X,XXX__XXX,X__XXXX_,
  ___XXX__,XXXX_XXX,X_XXXXX_,
  ____X___,_XXX_XXX,XXXXX___,
  ________,__X__XXX,X__X____,
  _______X,XXXXXXXX,XXXXXX__,
  __X____X,XXXXXXXX,XXXXXX__,
  _XXXX__X,XXXXXXXX,XXXXXX__,
  _XXXXX_X,XXX_____,___XXX__,
  __XXX__X,XXX_____,___XXX__,
  _______X,XXXXXXXX,XXXXXX__,
  _______X,XXXXXXXX,XXXXXX__,
  ___X___X,XXXXXXXX,XXXXXX__,
  __XXXX_X,XXX_____,___XXX__,
  __XXXX_X,XXX_____,___XXX__,
  __XXX__X,XXXXXXXX,XXXXXX__,
  __XXX__X,XXXXXXXX,XXXXXX__,
  __XXX__X,XXXXXXXX,XXXXXX__,
  _XXXX__X,XXX_____,___XXX__,
  _XXXX__X,XXX_____,___XXX__,
  _XXX___X,XXX____X,XXXXXX__,
  _XXX___X,XXX____X,XXXXXX__,
  __XX___X,XXX____X,XXXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_73AF[ 93] = { /* code 73AF */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  ___XXX__,______XX,X_______,
  ___XXX__,_____XXX,X_______,
  ___XXX__,_____XXX,________,
  ___XXX__,_____XXX,________,
  ___XXX__,____XXXX,X_______,
  _XXXXXXX,X___XXXX,X_XX____,
  _XXXXXXX,X__XXXXX,XXXX____,
  _XXXXXXX,X__XXXXX,X_XXX___,
  ___XXX__,__XXXXXX,X_XXX___,
  ___XXX__,_XXXX_XX,X__XXX__,
  ___XXX__,_XXX__XX,X__XXXX_,
  ___XXX__,XXXX__XX,X___XXX_,
  ___XXX__,XXX___XX,X___XXXX,
  ___XXXXX,X_____XX,X____X__,
  ___XXXXX,X_____XX,X_______,
  XXXXXXXX,X_____XX,X_______,
  XXXXXXXX,______XX,X_______,
  _XX_____,______XX,X_______,
  ________,______XX,X_______,
  ________,______XX,X_______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_7720[ 93] = { /* code 7720 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXX__XX,X_XXXXXX,XXXXXXX_,
  _XXX__XX,X_XXX___,____XXX_,
  _XXX__XX,X_XXX___,____XXX_,
  _XXX__XX,X_XXX___,____XXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXX__XX,X_XXXXXX,XXXXXXX_,
  _XXX__XX,X_XXX___,XX______,
  _XXX__XX,X_XXX___,XXX_____,
  _XXX__XX,X_XXX___,XXX_____,
  _XXXXXXX,X_XXXXXX,XXXXXXXX,
  _XXXXXXX,X_XXXXXX,XXXXXXXX,
  _XXX__XX,X_XXXXXX,XXXXXXXX,
  _XXX__XX,X_XXX___,XXX_____,
  _XXX__XX,X_XXX___,XXX___X_,
  _XXX__XX,X_XXX___,XXX__XXX,
  _XXXXXXX,X_XXX__X,_XXX_XXX,
  _XXXXXXX,X_XXXXXX,_XXX_XX_,
  _XXX__XX,XXXXXXXX,_XXXXXX_,
  _XXX__XX,X_XXXXX_,__XXXXX_,
  ________,__XX____,___XXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_7761[ 93] = { /* code 7761 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_XXXXX__,
  _XXXXXXX,_XXXXXXX,XXXXXX__,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XX______,
  _XXX_XXX,______XX,X_______,
  _XXX_XXX,XXXXXXXX,XXXXXXX_,
  _XXX_XXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,__XX__XX,X__XXX__,
  _XXX_XXX,__XX__XX,X__XXX__,
  _XXX_XXX,XXXXXXXX,XXXXXXXX,
  _XXX_XXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,
  _XXXXXXX,__XX__XX,X__XXX__,
  _XXX_XXX,__XX__XX,X__XXX__,
  _XXX_XXX,XXXXXXXX,XXXXXXX_,
  _XXX_XXX,XXXXXXXX,XXXXXXX_,
  _XXX_XXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,______XX,X_______,
  _XXXXXXX,______XX,X_______,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXX_XXX,_XXXXXXX,XXXXXXX_,
  ________,_XXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_786E[ 93] = { /* code 786E */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_____XX_,________,
  ________,____XXX_,________,
  _XXXXXXX,X___XXXX,XXXXX___,
  _XXXXXXX,X__XXXXX,XXXXX___,
  _XXXXXXX,X_XXXXXX,XXXXX___,
  ___XXX__,_XXXX___,_XXXX___,
  ___XXX__,XXXX____,_XXX____,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  __XXX___,XXXXXXXX,XXXXXXX_,
  __XXXXXX,__XXXXXX,XXXXXXX_,
  _XXXXXXX,__XX___X,X___XXX_,
  _XXXXXXX,__XX___X,X___XXX_,
  XXXXX_XX,__XXXXXX,XXXXXXX_,
  XXXXX_XX,__XXXXXX,XXXXXXX_,
  _XXXX_XX,__XX___X,X___XXX_,
  _XXXX_XX,__XX___X,X___XXX_,
  __XXX_XX,__XX___X,X___XXX_,
  __XXXXXX,_XXXXXXX,XXXXXXX_,
  __XXXXXX,_XXXXXXX,XXXXXXX_,
  __XXXXXX,_XXX___X,X___XXX_,
  __XXX___,_XXX___X,X___XXX_,
  __XXX___,XXXX___X,X_XXXXX_,
  ________,_XX____X,X_XXXXX_,
  ________,__X____X,X_XXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_793A[ 93] = { /* code 793A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___XXX__,________,
  _____X__,___XXX__,__X_____,
  _____XXX,___XXX__,XXX_____,
  ____XXXX,___XXX__,XXXX____,
  ___XXXX_,___XXX__,_XXXX___,
  ___XXXX_,___XXX__,_XXXX___,
  __XXXX__,___XXX__,__XXXX__,
  _XXXX___,___XXX__,___XXXX_,
  _XXXX___,___XXX__,___XXXX_,
  _XXX____,__XXXX__,____XXX_,
  __X___XX,XXXXXX__,____X___,
  _______X,XXXXXX__,________,
  _______X,XXXX____,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_7CFB[ 93] = { /* code 7CFB */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,_XXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XX______,
  ______XX,XXXX____,__X_____,
  ____XXXX,X_______,XXXX____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XXX__,__XXXXXX,X_______,
  ________,XXXXXXX_,_X______,
  ______XX,XXXXX___,XXX_____,
  ____XXXX,XXX_____,XXXX____,
  __XXXXXX,________,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,X__XXX__,____XXX_,
  ________,___XXX__,_____X__,
  _____X__,___XXX__,_XX_____,
  ____XXXX,___XXX__,_XXXX___,
  __XXXXXX,___XXX__,XXXXXX__,
  _XXXXX__,___XXX__,_XXXXXX_,
  _XXXX__X,XXXXXX__,___XXXX_,
  __X____X,XXXXXX__,_____X__,
  _______X,XXXXX___,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_7EDF[ 93] = { /* code 7EDF */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XX__,_____XXX,________,
  ____XXX_,_____XXX,X_______,
  ___XXXX_,_____XXX,X_______,
  ___XXX__,XXXXXXXX,XXXXXXX_,
  __XXXX__,XXXXXXXX,XXXXXXX_,
  __XXX___,XXXXXXXX,XXXXXXX_,
  _XXXX__X,____XXX_,________,
  _XXX__XX,X__XXX__,__XX____,
  XXXXXXXX,X_XXXX__,_XXXX___,
  _XXXXXXX,_XXXX___,__XXX___,
  _XXXXXX_,XXXXXXXX,XXXXXX__,
  ____XX__,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  __XXXXXX,___XXX__,XXX__X__,
  _XXXXXXX,___XXX__,XXX_____,
  _XXXXXXX,___XXX__,XXX_____,
  __XX____,___XXX__,XXX_____,
  ________,__XXXX__,XXX__X__,
  _____XXX,X_XXX___,XXX__XXX,
  _XXXXXXX,_XXXX___,XXX__XXX,
  _XXXXXXX,XXXXX___,XXX_XXX_,
  _XXXX__X,XXXX____,XXXXXXX_,
  ________,XXX_____,XXXXXXX_,
  ________,_X______,_XXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_7F6E[ 93] = { /* code 7F6E */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXX___,XXX__XXX,___XXX__,
  __XXX___,XXX__XXX,___XXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_80CC[ 93] = { /* code 80CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XX___XXX,________,
  _______X,XX___XXX,_____X__,
  _XXXXXXX,XX___XXX,__XXXXX_,
  _XXXXXXX,XX___XXX,XXXXXXX_,
  _______X,XX___XXX,XXXXXX__,
  _______X,XX___XXX,XXX__XX_,
  ___XXXXX,XX___XXX,_____XXX,
  XXXXXXXX,XX___XXX,____XXX_,
  _XXXXXXX,XX___XXX,XXXXXXX_,
  _XX____X,XX____XX,XXXXXX__,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,_XXXX___,
  ___XXX__,____XXXX,XXXXX___,
  ___XXX__,____XXXX,XXXXX___,
  ___XXX__,_____XXX,XXXX____,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_8BA4[ 93] = { /* code 8BA4 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,_____XXX,X_______,
  __XXXX__,_____XXX,X_______,
  __XXXXX_,_____XXX,X_______,
  ___XXXXX,_____XXX,X_______,
  ____XXX_,_____XXX,X_______,
  _____X__,_____XXX,X_______,
  ________,_____XXX,X_______,
  XXXXXX__,_____XXX,X_______,
  XXXXXX__,_____XXX,X_______,
  XXXXXX__,_____XXX,X_______,
  ___XXX__,_____XXX,X_______,
  ___XXX__,_____XXX,XX______,
  ___XXX__,_____XXX,XX______,
  ___XXX__,____XXXX,XX______,
  ___XXX__,X___XXXX,XXX_____,
  ___XXX_X,X___XXX_,XXX_____,
  ___XXXXX,X__XXXX_,XXX_____,
  ___XXXXX,X__XXX__,_XXX____,
  ___XXXXX,__XXXX__,_XXXX___,
  ___XXXX_,_XXXX___,__XXXX__,
  ___XXXX_,XXXXX___,__XXXXX_,
  __XXXX_X,XXXX____,___XXXX_,
  __XXX___,XXX_____,____XXX_,
  ___X____,_X______,_____X__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_8BBE[ 93] = { /* code 8BBE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,________,________,
  __XXX___,__XXXXXX,XXXX____,
  __XXXX__,__XXXXXX,XXXX____,
  ___XXXX_,__XXXXXX,XXXX____,
  ____XXX_,__XXX___,_XXX____,
  ____X___,_XXXX___,_XXX____,
  ________,XXXXX___,_XXXXXX_,
  _______X,XXXX____,_XXXXXX_,
  XXXXXX__,XXX_____,__XXXXX_,
  XXXXXX__,_XX_____,________,
  XXXXXX__,XXXXXXXX,XXXXXX__,
  ___XXX__,XXXXXXXX,XXXXXX__,
  ___XXX__,XXXXXXXX,XXXXXX__,
  ___XXX__,__XX____,__XXXX__,
  ___XXX__,_XXX____,_XXXX___,
  ___XXX_X,_XXXX___,_XXX____,
  ___XXXXX,__XXXX__,XXXX____,
  ___XXXXX,___XXXXX,XXX_____,
  ___XXXX_,____XXXX,XX______,
  __XXXXX_,___XXXXX,XX______,
  __XXXX__,_XXXXXXX,XXXXX___,
  ___XX_XX,XXXXXX__,XXXXXXX_,
  _______X,XXXX____,__XXXXX_,
  ________,XX______,____XX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_8C03[ 93] = { /* code 8C03 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  _XXXX__X,XXXXXXXX,XXXXXXX_,
  __XXX__X,XXXXXXXX,XXXXXXX_,
  __XXXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX_X,XX______,____XXX_,
  ___X___X,XX___XXX,____XXX_,
  _______X,XX___XXX,____XXX_,
  XXXXX__X,XX_XXXXX,XXX_XXX_,
  XXXXX__X,XX_XXXXX,XXX_XXX_,
  XXXXX__X,XX___XXX,____XXX_,
  __XXX__X,XXXXXXXX,XXX_XXX_,
  __XXX__X,XXXXXXXX,XXX_XXX_,
  __XXX__X,XX______,____XXX_,
  __XXX__X,XX_XXXXX,XXX_XXX_,
  __XXX__X,XX_XXXXX,XXX_XXX_,
  __XXXX_X,XX_XX___,XXX_XXX_,
  __XXXX_X,XX_XX___,XXX_XXX_,
  __XXXXXX,XX_XX___,XXX_XXX_,
  __XXX_XX,XX_XXXXX,XXX_XXX_,
  _XXX__XX,X__XXXXX,XXX_XXX_,
  __X___XX,X__XX___,___XXXX_,
  _____XXX,X_______,XXXXXX__,
  _____XXX,________,XXXXXX__,
  _______X,________,XXXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_9009[ 93] = { /* code 9009 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,______XX,X_______,
  _XXXX___,_XX___XX,X_______,
  __XXX___,_XXX__XX,X_______,
  __XXXX__,_XXX__XX,X_______,
  ___XXXX_,XXXXXXXX,XXXXXX__,
  ____XX__,XXXXXXXX,XXXXXX__,
  ____X___,XXXXXXXX,XXXXXX__,
  _______X,XX____XX,X_______,
  ________,_X____XX,X_______,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  _XXXXX_X,XXXXXXXX,XXXXXXX_,
  ___XXX__,__XXX__X,XX______,
  ___XXX__,__XXX__X,XX__X___,
  ___XXX__,__XXX__X,XX__XXX_,
  ___XXX__,_XXXX__X,XX__XXX_,
  ___XXX__,XXXX___X,XXXXXXX_,
  ___XXX__,XXX____X,XXXXXX__,
  __XXXXX_,_X______,XXXXXX__,
  __XXXXXX,X_______,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX__XX,XXXXXXXX,XXXXXXX_,
  _XX_____,XXXXXXXX,XXXXXXX_,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_949F[ 93] = { /* code 949F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,_______X,XX______,
  ___XXX__,_______X,XX______,
  ___XXX__,_______X,XX______,
  __XXXXXX,X______X,XX______,
  __XXXXXX,X______X,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  _XXX____,_XXXXXXX,XXXXXXX_,
  _XXX____,_XXXXXXX,XXXXXXX_,
  XXXXXXXX,_XXXX__X,XX__XXX_,
  _XXXXXXX,_XXXX__X,XX__XXX_,
  _XXXXXXX,_XXXX__X,XX__XXX_,
  _X_XXX__,_XXXX__X,XX__XXX_,
  ___XXX__,_XXXX__X,XX__XXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ___XXX__,_XXXX__X,XX__XXX_,
  ___XXX__,_XXXX__X,XX__XXX_,
  ___XXX__,X______X,XX______,
  ___XXXXX,X______X,XX______,
  ___XXXXX,X______X,XX______,
  ___XXXXX,_______X,XX______,
  ___XXX__,_______X,XX______,
  ____X___,_______X,XX______,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_94AE[ 93] = { /* code 94AE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXX__,________,________,
  ___XX___,__XXXXXX,XXXXXXX_,
  __XXXXXX,X_XXXXXX,XXXXXXX_,
  __XXXXXX,X_XXXXXX,XXXXXXX_,
  __XXXXXX,X___XXX_,___XXXX_,
  _XXX____,____XXX_,___XXX__,
  _XXX____,____XXX_,___XXX__,
  _XXXXXXX,____XXX_,___XXX__,
  XXXXXXXX,____XXX_,___XXX__,
  _XXXXXXX,____XXX_,___XXX__,
  _X_XXX__,_XXXXXXX,XXXXXX__,
  _X_XXX__,_XXXXXXX,XXXXXX__,
  ___XXX__,_XXXXXXX,XXXXXX__,
  XXXXXXXX,X___XXX_,___XXX__,
  XXXXXXXX,X___XXX_,___XXX__,
  XXXXXXXX,X___XXX_,___XXX__,
  ___XXX__,___XXXX_,___XXX__,
  ___XXX__,___XXXX_,___XXX__,
  ___XXX_X,X__XXXX_,___XXX__,
  ___XXXXX,X__XXX__,___XXX__,
  ___XXXXX,XXXXXXXX,XXXXXXX_,
  ___XXXXX,_XXXXXXX,XXXXXXX_,
  ___XXX__,_XXXXXXX,XXXXXXX_,
  ____X___,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_952E[ 93] = { /* code 952E */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,________,XX______,
  __XXX___,________,XX______,
  __XXX__X,XXXX_XXX,XXXXXXX_,
  __XXX__X,XXXX_XXX,XXXXXXX_,
  __XXXXXX,XXXX____,XX__XXX_,
  _XXXXXX_,_XXXXXXX,XXXXXXX_,
  _XXXXXX_,_XXXXXXX,XXXXXXX_,
  XXX_____,XXX_____,XX__XXX_,
  XXXXXXX_,XX___XXX,XXXXXXX_,
  _XXXXXXX,XXXX_XXX,XXXXXXX_,
  _XXXXXXX,XXXX____,XX______,
  __XXX__X,XXXX_XXX,XXXXXXX_,
  __XXX___,__XX_XXX,XXXXXXX_,
  XXXXXXX_,__XX____,XX______,
  XXXXXXX_,__XX____,XX______,
  XXXXXXXX,X_XXXXXX,XXXXXXX_,
  __XXX__X,XXXXXXXX,XXXXXXX_,
  __XXX_XX,XXX_____,XX______,
  __XXXXX_,XXXX____,XX______,
  __XXXXX_,XXXXXX__,________,
  __XXXX_X,XXXXXXXX,XXXXXXXX,
  __XXX_XX,XX_XXXXX,XXXXXXX_,
  ___X_XXX,X____XXX,XXXXXXX_,
  _______X,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_95F4[ 93] = { /* code 95F4 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ______X_,________,________,
  ____XXXX,__XXXXXX,XXXXXXX_,
  _____XXX,X_XXXXXX,XXXXXXX_,
  _XXXXXXX,X_XXXXXX,XXXXXXX_,
  _XXXX_X_,________,___XXXX_,
  _XXXX___,________,___XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XX____XX,X__XXXX_,
  _XXXX__X,XX____XX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XX____XX,X__XXXX_,
  _XXXX__X,XX____XX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XXXXXXXX,X__XXXX_,
  _XXXX__X,XX______,___XXXX_,
  _XXXX___,________,___XXXX_,
  _XXXX___,______XX,XXXXXX__,
  _XXXX___,______XX,XXXXXX__,
  _XXXX___,_______X,XXXXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_9694[ 93] = { /* code 9694 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXX__XX,________,________,
  _XXX_XXX,__XXXXXX,XXXXXX__,
  _XXX_XXX,__XXXXXX,XXXXXX__,
  _XXX_XXX,__XXX___,___XXX__,
  _XXX_XX_,__XXX___,___XXX__,
  _XXX_XX_,__XXXXXX,XXXXXX__,
  _XXXXXXX,__XXXXXX,XXXXXX__,
  _XXX_XXX,________,________,
  _XXX__XX,_XXXXXXX,XXXXXXX_,
  _XXX__XX,XXXXXXXX,XXXXXXX_,
  _XXX__XX,XXXXXXXX,XXXXXXX_,
  _XXX__XX,XXXX_XX_,_XX_XXX_,
  _XXX__XX,XXXX_XX_,XXX_XXX_,
  _XXXXXXX,XXXX_XXX,XX__XXX_,
  _XXXXXXX,_XXXXXXX,XXXXXXX_,
  _XXX_XX_,_XXXXXXX,XXXXXXX_,
  _XXX____,_XXX___X,X___XXX_,
  _XXX____,_XXX___X,X_XXXXX_,
  _XXX____,_XXX___X,X_XXXXX_,
  _XXX____,_XXX___X,X_XXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_97F3[ 93] = { /* code 97F3 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXX___,________,
  ________,__XXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ______XX,X______X,XX______,
  ______XX,XX____XX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ___XXX__,________,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,__XXX___,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_9884[ 93] = { /* code 9884 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XX_XXXXX,XXXXXXX_,
  _XXXXXXX,XX_XXXXX,XXXXXXX_,
  _XXXXXXX,XX_XXXXX,XXXXXXX_,
  ______XX,XX_____X,XX______,
  __X___XX,X______X,XX______,
  _XXX_XXX,___XXXXX,XXXXXXX_,
  __XXXXXX,___XXXXX,XXXXXXX_,
  ___XXXX_,___XXXXX,XXXXXXX_,
  XXXXXXXX,XX_XXX__,____XXX_,
  XXXXXXXX,XX_XXX_X,XX__XXX_,
  XXXXXXXX,XX_XXX_X,XX__XXX_,
  ___XXX__,XX_XXX_X,XX__XXX_,
  ___XXX__,XX_XXX_X,XX__XXX_,
  ___XXX__,XX_XXX_X,XX__XXX_,
  ___XXX_X,XX_XXX_X,XX__XXX_,
  ___XXX_X,XX_XXX_X,XX__XXX_,
  ___XXX__,___XXXXX,XXX_XXX_,
  ___XXX__,_____XXX,XXXX____,
  ___XXX__,____XXXX,XXXXX___,
  ___XXX__,___XXXXX,__XXXX__,
  _XXXXX__,__XXXXX_,___XXXX_,
  _XXXXX__,__XXXX__,____XXX_,
  _XXXX___,___X____,_____X__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYH31_98CE[ 93] = { /* code 98CE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __XXXX__,________,_XXX____,
  __XXXX_X,X_____X_,_XXX____,
  __XXXXXX,X_____XX,XXXX____,
  __XXXXXX,XX___XXX,XXXX____,
  __XXXX_X,XX__XXXX,_XXX____,
  __XXXX__,XXX_XXX_,_XXX____,
  __XXXX__,XXXXXXX_,_XXX____,
  __XXXX__,_XXXXX__,_XXX____,
  __XXXX__,_XXXXX__,_XXX____,
  __XXXX__,_XXXXX__,_XXX____,
  __XXX___,XXXXXXX_,_XXX____,
  __XXX__X,XXX_XXX_,_XXX____,
  __XXX__X,XXX_XXXX,_XXX__X_,
  __XXX_XX,XX___XXX,_XXX__XX,
  __XXXXXX,X____XXX,XXXX__XX,
  _XXXX_XX,X_____XX,XXXX__XX,
  _XXX___X,______X_,__XXXXXX,
  XXXX____,________,__XXXXX_,
  _XX_____,________,__XXXXX_,
  __X_____,________,___XXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYH31_CharInfo[63] = {
   {  24,  24,  3, acGUI_FontYH31_4E00 } /* code 4E00 */
  ,{  24,  24,  3, acGUI_FontYH31_4E09 } /* code 4E09 */
  ,{  24,  24,  3, acGUI_FontYH31_4E8C } /* code 4E8C */
  ,{  24,  24,  3, acGUI_FontYH31_4E94 } /* code 4E94 */
  ,{  24,  24,  3, acGUI_FontYH31_4EAE } /* code 4EAE */
  ,{  24,  24,  3, acGUI_FontYH31_4F5C } /* code 4F5C */
  ,{  24,  24,  3, acGUI_FontYH31_5149 } /* code 5149 */
  ,{  24,  24,  3, acGUI_FontYH31_5168 } /* code 5168 */
  ,{  24,  24,  3, acGUI_FontYH31_516D } /* code 516D */
  ,{  24,  24,  3, acGUI_FontYH31_5173 } /* code 5173 */
  ,{  24,  24,  3, acGUI_FontYH31_51C0 } /* code 51C0 */
  ,{  24,  24,  3, acGUI_FontYH31_51C6 } /* code 51C6 */
  ,{  24,  24,  3, acGUI_FontYH31_5206 } /* code 5206 */
  ,{  24,  24,  3, acGUI_FontYH31_5316 } /* code 5316 */
  ,{  24,  24,  3, acGUI_FontYH31_53CD } /* code 53CD */
  ,{  24,  24,  3, acGUI_FontYH31_53D6 } /* code 53D6 */
  ,{  24,  24,  3, acGUI_FontYH31_56DB } /* code 56DB */
  ,{  24,  24,  3, acGUI_FontYH31_5A74 } /* code 5A74 */
  ,{  24,  24,  3, acGUI_FontYH31_5C4F } /* code 5C4F */
  ,{  24,  24,  3, acGUI_FontYH31_5DE5 } /* code 5DE5 */
  ,{  24,  24,  3, acGUI_FontYH31_5E55 } /* code 5E55 */
  ,{  24,  24,  3, acGUI_FontYH31_5E74 } /* code 5E74 */
  ,{  24,  24,  3, acGUI_FontYH31_5EA6 } /* code 5EA6 */
  ,{  24,  24,  3, acGUI_FontYH31_5F00 } /* code 5F00 */
  ,{  24,  24,  3, acGUI_FontYH31_5F0F } /* code 5F0F */
  ,{  24,  24,  3, acGUI_FontYH31_5FAA } /* code 5FAA */
  ,{  24,  24,  3, acGUI_FontYH31_6094 } /* code 6094 */
  ,{  24,  24,  3, acGUI_FontYH31_62E9 } /* code 62E9 */
  ,{  24,  24,  3, acGUI_FontYH31_6309 } /* code 6309 */
  ,{  24,  24,  3, acGUI_FontYH31_63D0 } /* code 63D0 */
  ,{  24,  24,  3, acGUI_FontYH31_6574 } /* code 6574 */
  ,{  24,  24,  3, acGUI_FontYH31_65B0 } /* code 65B0 */
  ,{  24,  24,  3, acGUI_FontYH31_65E5 } /* code 65E5 */
  ,{  24,  24,  3, acGUI_FontYH31_65F6 } /* code 65F6 */
  ,{  24,  24,  3, acGUI_FontYH31_661F } /* code 661F */
  ,{  24,  24,  3, acGUI_FontYH31_6708 } /* code 6708 */
  ,{  24,  24,  3, acGUI_FontYH31_671F } /* code 671F */
  ,{  24,  24,  3, acGUI_FontYH31_673A } /* code 673A */
  ,{  24,  24,  3, acGUI_FontYH31_6807 } /* code 6807 */
  ,{  24,  24,  3, acGUI_FontYH31_6A21 } /* code 6A21 */
  ,{  24,  24,  3, acGUI_FontYH31_6BCD } /* code 6BCD */
  ,{  24,  24,  3, acGUI_FontYH31_6D88 } /* code 6D88 */
  ,{  24,  24,  3, acGUI_FontYH31_73AF } /* code 73AF */
  ,{  24,  24,  3, acGUI_FontYH31_7720 } /* code 7720 */
  ,{  24,  24,  3, acGUI_FontYH31_7761 } /* code 7761 */
  ,{  24,  24,  3, acGUI_FontYH31_786E } /* code 786E */
  ,{  24,  24,  3, acGUI_FontYH31_793A } /* code 793A */
  ,{  24,  24,  3, acGUI_FontYH31_7CFB } /* code 7CFB */
  ,{  24,  24,  3, acGUI_FontYH31_7EDF } /* code 7EDF */
  ,{  24,  24,  3, acGUI_FontYH31_7F6E } /* code 7F6E */
  ,{  24,  24,  3, acGUI_FontYH31_80CC } /* code 80CC */
  ,{  24,  24,  3, acGUI_FontYH31_8BA4 } /* code 8BA4 */
  ,{  24,  24,  3, acGUI_FontYH31_8BBE } /* code 8BBE */
  ,{  24,  24,  3, acGUI_FontYH31_8C03 } /* code 8C03 */
  ,{  24,  24,  3, acGUI_FontYH31_9009 } /* code 9009 */
  ,{  24,  24,  3, acGUI_FontYH31_949F } /* code 949F */
  ,{  24,  24,  3, acGUI_FontYH31_94AE } /* code 94AE */
  ,{  24,  24,  3, acGUI_FontYH31_952E } /* code 952E */
  ,{  24,  24,  3, acGUI_FontYH31_95F4 } /* code 95F4 */
  ,{  24,  24,  3, acGUI_FontYH31_9694 } /* code 9694 */
  ,{  24,  24,  3, acGUI_FontYH31_97F3 } /* code 97F3 */
  ,{  24,  24,  3, acGUI_FontYH31_9884 } /* code 9884 */
  ,{  24,  24,  3, acGUI_FontYH31_98CE } /* code 98CE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop63 = {
   0x98CE /* first character */
  ,0x98CE /* last character  */
  ,&GUI_FontYH31_CharInfo[ 62] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop62 = {
   0x9884 /* first character */
  ,0x9884 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 61] /* address of first character */
  ,&GUI_FontYH31_Prop63 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop61 = {
   0x97F3 /* first character */
  ,0x97F3 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 60] /* address of first character */
  ,&GUI_FontYH31_Prop62 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop60 = {
   0x9694 /* first character */
  ,0x9694 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 59] /* address of first character */
  ,&GUI_FontYH31_Prop61 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop59 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 58] /* address of first character */
  ,&GUI_FontYH31_Prop60 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop58 = {
   0x952E /* first character */
  ,0x952E /* last character  */
  ,&GUI_FontYH31_CharInfo[ 57] /* address of first character */
  ,&GUI_FontYH31_Prop59 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop57 = {
   0x94AE /* first character */
  ,0x94AE /* last character  */
  ,&GUI_FontYH31_CharInfo[ 56] /* address of first character */
  ,&GUI_FontYH31_Prop58 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop56 = {
   0x949F /* first character */
  ,0x949F /* last character  */
  ,&GUI_FontYH31_CharInfo[ 55] /* address of first character */
  ,&GUI_FontYH31_Prop57 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop55 = {
   0x9009 /* first character */
  ,0x9009 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 54] /* address of first character */
  ,&GUI_FontYH31_Prop56 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop54 = {
   0x8C03 /* first character */
  ,0x8C03 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 53] /* address of first character */
  ,&GUI_FontYH31_Prop55 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop53 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontYH31_CharInfo[ 52] /* address of first character */
  ,&GUI_FontYH31_Prop54 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop52 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 51] /* address of first character */
  ,&GUI_FontYH31_Prop53 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop51 = {
   0x80CC /* first character */
  ,0x80CC /* last character  */
  ,&GUI_FontYH31_CharInfo[ 50] /* address of first character */
  ,&GUI_FontYH31_Prop52 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop50 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontYH31_CharInfo[ 49] /* address of first character */
  ,&GUI_FontYH31_Prop51 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop49 = {
   0x7EDF /* first character */
  ,0x7EDF /* last character  */
  ,&GUI_FontYH31_CharInfo[ 48] /* address of first character */
  ,&GUI_FontYH31_Prop50 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop48 = {
   0x7CFB /* first character */
  ,0x7CFB /* last character  */
  ,&GUI_FontYH31_CharInfo[ 47] /* address of first character */
  ,&GUI_FontYH31_Prop49 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop47 = {
   0x793A /* first character */
  ,0x793A /* last character  */
  ,&GUI_FontYH31_CharInfo[ 46] /* address of first character */
  ,&GUI_FontYH31_Prop48 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop46 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_FontYH31_CharInfo[ 45] /* address of first character */
  ,&GUI_FontYH31_Prop47 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop45 = {
   0x7761 /* first character */
  ,0x7761 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 44] /* address of first character */
  ,&GUI_FontYH31_Prop46 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop44 = {
   0x7720 /* first character */
  ,0x7720 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 43] /* address of first character */
  ,&GUI_FontYH31_Prop45 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop43 = {
   0x73AF /* first character */
  ,0x73AF /* last character  */
  ,&GUI_FontYH31_CharInfo[ 42] /* address of first character */
  ,&GUI_FontYH31_Prop44 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop42 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 41] /* address of first character */
  ,&GUI_FontYH31_Prop43 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop41 = {
   0x6BCD /* first character */
  ,0x6BCD /* last character  */
  ,&GUI_FontYH31_CharInfo[ 40] /* address of first character */
  ,&GUI_FontYH31_Prop42 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop40 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 39] /* address of first character */
  ,&GUI_FontYH31_Prop41 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop39 = {
   0x6807 /* first character */
  ,0x6807 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 38] /* address of first character */
  ,&GUI_FontYH31_Prop40 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop38 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontYH31_CharInfo[ 37] /* address of first character */
  ,&GUI_FontYH31_Prop39 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop37 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontYH31_CharInfo[ 36] /* address of first character */
  ,&GUI_FontYH31_Prop38 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop36 = {
   0x6708 /* first character */
  ,0x6708 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 35] /* address of first character */
  ,&GUI_FontYH31_Prop37 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop35 = {
   0x661F /* first character */
  ,0x661F /* last character  */
  ,&GUI_FontYH31_CharInfo[ 34] /* address of first character */
  ,&GUI_FontYH31_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop34 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 33] /* address of first character */
  ,&GUI_FontYH31_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop33 = {
   0x65E5 /* first character */
  ,0x65E5 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 32] /* address of first character */
  ,&GUI_FontYH31_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop32 = {
   0x65B0 /* first character */
  ,0x65B0 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 31] /* address of first character */
  ,&GUI_FontYH31_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop31 = {
   0x6574 /* first character */
  ,0x6574 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 30] /* address of first character */
  ,&GUI_FontYH31_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop30 = {
   0x63D0 /* first character */
  ,0x63D0 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 29] /* address of first character */
  ,&GUI_FontYH31_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop29 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 28] /* address of first character */
  ,&GUI_FontYH31_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop28 = {
   0x62E9 /* first character */
  ,0x62E9 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 27] /* address of first character */
  ,&GUI_FontYH31_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop27 = {
   0x6094 /* first character */
  ,0x6094 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 26] /* address of first character */
  ,&GUI_FontYH31_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop26 = {
   0x5FAA /* first character */
  ,0x5FAA /* last character  */
  ,&GUI_FontYH31_CharInfo[ 25] /* address of first character */
  ,&GUI_FontYH31_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop25 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontYH31_CharInfo[ 24] /* address of first character */
  ,&GUI_FontYH31_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop24 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 23] /* address of first character */
  ,&GUI_FontYH31_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop23 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 22] /* address of first character */
  ,&GUI_FontYH31_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop22 = {
   0x5E74 /* first character */
  ,0x5E74 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 21] /* address of first character */
  ,&GUI_FontYH31_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop21 = {
   0x5E55 /* first character */
  ,0x5E55 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 20] /* address of first character */
  ,&GUI_FontYH31_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop20 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 19] /* address of first character */
  ,&GUI_FontYH31_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop19 = {
   0x5C4F /* first character */
  ,0x5C4F /* last character  */
  ,&GUI_FontYH31_CharInfo[ 18] /* address of first character */
  ,&GUI_FontYH31_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop18 = {
   0x5A74 /* first character */
  ,0x5A74 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 17] /* address of first character */
  ,&GUI_FontYH31_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop17 = {
   0x56DB /* first character */
  ,0x56DB /* last character  */
  ,&GUI_FontYH31_CharInfo[ 16] /* address of first character */
  ,&GUI_FontYH31_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop16 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 15] /* address of first character */
  ,&GUI_FontYH31_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop15 = {
   0x53CD /* first character */
  ,0x53CD /* last character  */
  ,&GUI_FontYH31_CharInfo[ 14] /* address of first character */
  ,&GUI_FontYH31_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop14 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 13] /* address of first character */
  ,&GUI_FontYH31_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop13 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 12] /* address of first character */
  ,&GUI_FontYH31_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop12 = {
   0x51C6 /* first character */
  ,0x51C6 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 11] /* address of first character */
  ,&GUI_FontYH31_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop11 = {
   0x51C0 /* first character */
  ,0x51C0 /* last character  */
  ,&GUI_FontYH31_CharInfo[ 10] /* address of first character */
  ,&GUI_FontYH31_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop10 = {
   0x5173 /* first character */
  ,0x5173 /* last character  */
  ,&GUI_FontYH31_CharInfo[  9] /* address of first character */
  ,&GUI_FontYH31_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop9 = {
   0x516D /* first character */
  ,0x516D /* last character  */
  ,&GUI_FontYH31_CharInfo[  8] /* address of first character */
  ,&GUI_FontYH31_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop8 = {
   0x5168 /* first character */
  ,0x5168 /* last character  */
  ,&GUI_FontYH31_CharInfo[  7] /* address of first character */
  ,&GUI_FontYH31_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop7 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_FontYH31_CharInfo[  6] /* address of first character */
  ,&GUI_FontYH31_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop6 = {
   0x4F5C /* first character */
  ,0x4F5C /* last character  */
  ,&GUI_FontYH31_CharInfo[  5] /* address of first character */
  ,&GUI_FontYH31_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop5 = {
   0x4EAE /* first character */
  ,0x4EAE /* last character  */
  ,&GUI_FontYH31_CharInfo[  4] /* address of first character */
  ,&GUI_FontYH31_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop4 = {
   0x4E94 /* first character */
  ,0x4E94 /* last character  */
  ,&GUI_FontYH31_CharInfo[  3] /* address of first character */
  ,&GUI_FontYH31_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop3 = {
   0x4E8C /* first character */
  ,0x4E8C /* last character  */
  ,&GUI_FontYH31_CharInfo[  2] /* address of first character */
  ,&GUI_FontYH31_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop2 = {
   0x4E09 /* first character */
  ,0x4E09 /* last character  */
  ,&GUI_FontYH31_CharInfo[  1] /* address of first character */
  ,&GUI_FontYH31_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYH31_Prop1 = {
   0x4E00 /* first character */
  ,0x4E00 /* last character  */
  ,&GUI_FontYH31_CharInfo[  0] /* address of first character */
  ,&GUI_FontYH31_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYH31 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,31 /* height of font  */
  ,31 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYH31_Prop1}
  ,25 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

